version: "3"
services:
  # Database
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "!rootpasswd!"
      MYSQL_USER: "ava"
      MYSQL_PASSWORD: "!ava_app!"
      MYSQL_DATABASE: "app"

  # Database viewer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  # RabbitMQ message broker
  rabbitmq:
    image: rabbitmq:3.11.0-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=ava
      - RABBITMQ_DEFAULT_PASS=!ava_app!

  # # Backend (for docker buid testing only)
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   restart: always
  #   environment:
  #     AVA__VERSION: 0.1
  #     # Connection string uses Docker DNS name for the database (db)
  #     AVA__CONNECTIONSTRING: "Server=db;Database=app;Uid=ava;Pwd=!ava_app!;"
  #     AVA__JWTKEY: DevelopmentKey!!
  #     AVA__RABBITMQ__HOST: rabbitmq
  #     AVA__RABBITMQ__USER: ava
  #     AVA__RABBITMQ__PASSWORD: "!ava_app!"
  #   ports:
  #     - 5000:80
  #   depends_on:
  #     - rabbitmq
  #     - db

  # Simulation (for docker buid testing only)
  # sim:
  #   build:
  #     context: ./simulation
  #     dockerfile: Dockerfile
  #   restart: always
  #   environment:
  #     - AVA__RABBITMQ__HOST=rabbitmq
  #     - AVA__RABBITMQ__USER=ava
  #     - AVA__RABBITMQ__PASS=!ava_app!
  #     - AVA__RABBITMQ__PORT=5672
  #   depends_on:
  #     - rabbitmq
