version: "3"
services:
  # Database
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "!rootpasswd!"
      MYSQL_USER: "ava"
      MYSQL_PASSWORD: "!ava_app!"
      MYSQL_DATABASE: "app"

  # Database viewer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
