# version: "3"
# services:
#   # Database
#   db:
#     image: mysql:8.0
#     command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
#     restart: always
#     ports:
#       - ${Snappy__Database__Port}:3306
#     environment:
#       MYSQL_ROOT_PASSWORD: ${Snappy__Database__RootPassword}
#       MYSQL_USER: ${Snappy__Database__Username}
#       MYSQL_PASSWORD: ${Snappy__Database__Password}
#       MYSQL_DATABASE: ${Snappy__Database__DatabaseName}
#   # Database viewer
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080
#   # api:
#   #   container_name: audex
#   #   build:
#   #     context: ./Audex.API
#   #     dockerfile: ./Audex.API/Dockerfile
#   #   volumes:
#   #     - ./LocorumBackend.API:/app/LocorumBackend.API
#   #     - ./LocorumBackend.Models:/app/LocorumBackend.Models
#   #   environment:
#   #     - DOTNET_USE_POLLING_FILE_WATCHER=1
#   #     - DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2
#   #     - DOTNET_CLI_TELEMETRY_OPTOUT=1
#   #     - AUDEX_DEVELOPMENT=1
#   #   ports:
#   #       - "5000:5000"
