name: Trigger auto deployment for avabackend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - 'backend/**'
    - '.github/workflows/avabackend-AutoDeployTrigger-9d216480-fffd-4327-be8f-608394b7fdbb.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: avacontainers.azurecr.io
          username: ${{ secrets.AVABACKEND_REGISTRY_USERNAME }}
          password: ${{ secrets.AVABACKEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: avacontainers.azurecr.io/avabackend:${{ github.sha }}
          file: ./backend/Dockerfile
          context: ./backend/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AVABACKEND_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n avabackend -g Backend --server avacontainers.azurecr.io --username  ${{ secrets.AVABACKEND_REGISTRY_USERNAME }} --password ${{ secrets.AVABACKEND_REGISTRY_PASSWORD }}
            az containerapp update -n avabackend -g Backend --image avacontainers.azurecr.io/avabackend:${{ github.sha }}
